version: '3'

services:
  myApp:
    container_name: myApp
    build: 
      context: .
    environment:
      - BOX_SERVER_CFCONFIGFILE=/app/cfconfig.json
    ports:
      - 8080:8080
    volumes:
      - ./:/app
